# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.11.1
_src_path: gh:algorandfoundation/algokit-beaker-default-template
algod_port: 4001
algod_server: http://localhost
algod_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
author_email: ''
author_name: Jehuda
contract_name: hello_world
deployment_language: python
ide_vscode: true
indexer_port: 8980
indexer_server: http://localhost
indexer_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
preset_name: starter
project_name: hello_world_demo
use_python_black: true
use_python_pytest: true

